{
 "title": "zeebe workflow",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "seconds metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(job)(rate(zeebe_running_workflow_instances_total[1m]))"
    },
    {
     "expr": "deriv(zeebe_running_workflow_instances_total[1m])"
    },
    {
     "expr": "rate(grpc_server_started_total{instance=~\"$instance\"}[1m]) ",
     "legendFormat": "{{grpc_method}}--{{grpc_type}}--{{instance}}"
    }
   ]
  },
  {
   "title": "deriv(zeebe_running_workflow_instances_total[1m])",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(zeebe_running_workflow_instances_total[1m])"
    }
   ]
  },
  {
   "title": "sum by(job)(rate(zeebe_running_workflow_instances_total[1m]))",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(job)(rate(zeebe_running_workflow_instances_total[1m]))"
    }
   ]
  },
  {
   "title": "grpc_server_started_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_server_started_total{instance=~\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "jvm_threads_state",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_state{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "zeebe_received_request_count_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (zeebe_received_request_count_total)"
    }
   ]
  },
  {
   "title": "grpc_server_started_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_server_started_total{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "zeebe_received_request_count_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (zeebe_received_request_count_total)"
    }
   ]
  },
  {
   "title": "grpc_server_handled_latency_seconds_bucket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_server_handled_latency_seconds_bucket{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "zeebe_job_events_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (zeebe_job_events_total)"
    }
   ]
  },
  {
   "title": "zeebe_running_workflow_instances_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zeebe_running_workflow_instances_total{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "zeebe_running_workflow_instances_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance)(zeebe_running_workflow_instances_total)"
    }
   ]
  },
  {
   "title": "grpc_server_handled_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_server_handled_total{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "zeebe_running_workflow_instances_total second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(zeebe_running_workflow_instances_total[1m])",
     "legendFormat": "{{instance}}--{{partition}}"
    }
   ]
  },
  {
   "title": "grpc_server_handled_latency_seconds_bucket",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "grpc_server_handled_latency_seconds_bucket{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "jvm_threads_state",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "jvm_threads_state" }
   ]
  },
  {
   "title": "zeebe_stream_processor_latency_sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zeebe_stream_processor_latency_sum"
    }
   ]
  },
  {
   "title": "zeebe_exporter_events_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zeebe_exporter_events_total{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "jvm_threads_current",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "zeebe_stream_processor_latency_sum",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zeebe_stream_processor_latency_sum{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "zeebe_stream_processor_latency_bucket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "zeebe_stream_processor_latency_bucket"
    }
   ]
  }
 ]
}